// Vue/mybooks-vue/src/components/sideBar.vue
<template>
  <aside class="sidebar">
    <RouterLink to="/" class="brand" aria-label="Ir al inicio">
      <span class="brand-mark">M</span>
      <span>
        <strong>MyBooks</strong>
        <small>Biblioteca personal</small>
      </span>
    </RouterLink>

    <nav class="sidebar-nav" aria-label="Navegacion principal">
      <RouterLink to="/" class="nav-item">
        <span class="nav-icon" aria-hidden="true">⌂</span>
        Inicio
      </RouterLink>
      <RouterLink to="/explore" class="nav-item">
        <span class="nav-icon" aria-hidden="true">⌕</span>
        Explorar
      </RouterLink>
      <RouterLink to="/library" class="nav-item">
        <span class="nav-icon" aria-hidden="true">▥</span>
        Mi biblioteca
      </RouterLink>
      <RouterLink to="/roulette" class="nav-item nav-accent">
        <span class="nav-icon" aria-hidden="true">✳</span>
        Ruleta
      </RouterLink>
    </nav>
  </aside>
</template>

<script setup>
</script>

<style scoped>
.sidebar {
  position: sticky;
  top: 0;
  display: flex;
  width: 260px;
  height: 100vh;
  flex: 0 0 260px;
  flex-direction: column;
  gap: 34px;
  padding: 30px 20px 22px;
  background: var(--paper-2);
  border-right: 1px solid var(--line);
}

.brand {
  display: flex;
  align-items: center;
  gap: 14px;
  color: var(--ink);
  text-decoration: none;
}

.brand-mark {
  display: grid;
  width: 42px;
  height: 42px;
  place-items: center;
  border-radius: 11px;
  background: var(--ink);
  color: var(--gold);
  font-family: Georgia, "Times New Roman", serif;
  font-size: 24px;
  font-style: italic;
  line-height: 1;
}

.brand strong {
  display: block;
  font-family: Georgia, "Times New Roman", serif;
  font-size: 25px;
  line-height: 1;
}

.brand small {
  display: block;
  margin-top: 5px;
  color: var(--ink-soft);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.13em;
  line-height: 1.25;
  text-transform: uppercase;
}

.sidebar-nav {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.nav-item {
  display: flex;
  align-items: center;
  gap: 13px;
  padding: 14px 16px;
  border-radius: 10px;
  color: var(--ink);
  font-size: 17px;
  font-weight: 600;
  text-decoration: none;
  transition: background 0.18s ease, color 0.18s ease;
}

.nav-icon {
  width: 22px;
  color: currentColor;
  font-size: 20px;
  line-height: 1;
  text-align: center;
}

.nav-item:hover,
.nav-item.router-link-active {
  background: var(--ink);
  color: var(--paper-2);
}

.nav-accent {
  color: var(--coffee);
}

@media (max-width: 768px) {
  .sidebar {
    position: static;
    width: 100%;
    height: auto;
    flex-basis: auto;
    padding: 18px;
    border-right: 0;
    border-bottom: 1px solid var(--line);
  }

  .sidebar-nav {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

}
</style>

// Svelte/frontend/MyBooks/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import Icon from '../ui/Icon.svelte';

  const NAV = [
    { path: '/',                    label: 'Inicio',        icon: 'home'    },
    { path: '/explorar',            label: 'Explorar',      icon: 'compass' },
    { path: '/biblioteca',          label: 'Mi biblioteca', icon: 'books'   },
    { path: '/biblioteca/wishlist', label: 'Quiero leer',   icon: 'heart'   },
    { path: '/ruleta',              label: 'Ruleta',        icon: 'dice', magic: true },
  ];

  const currentPath = $derived($page.url.pathname);
</script>

<aside style="
  width: 264px; flex: none; height: 100vh;
  position: sticky; top: 0;
  background: var(--paper-2); border-right: 1px solid var(--line);
  display: flex; flex-direction: column;
  z-index: 70; overflow-y: auto;
">
  <!-- logo -->
  <div style="padding: 30px 22px 22px;">
    <button
      onclick={() => goto('/')}
      style="display: flex; align-items: center; gap: 11px; cursor: pointer; background: none; border: none; padding: 0;"
    >
      <div style="
        width: 38px; height: 38px; border-radius: 10px;
        background: var(--ink); color: var(--gold);
        display: grid; place-items: center; flex: none;
        font-family: 'Newsreader', serif; font-size: 22px;
        font-weight: 600; font-style: italic;
      ">M</div>
      <div>
        <div style="font-family: 'Newsreader', serif; font-size: 22px; font-weight: 600; color: var(--ink); line-height: 1;">MyBooks</div>
      </div>
    </button>
  </div>

  <!-- navegación -->
  <nav style="padding: 0 14px; display: flex; flex-direction: column; gap: 3px; flex: 1;">
    {#each NAV as item}
      {@const active = currentPath === item.path}
      <button
        onclick={() => goto(item.path)}
        style="
          display: flex; align-items: center; gap: 12px;
          width: 100%; text-align: left; cursor: pointer;
          font-family: 'DM Sans', sans-serif; font-size: 15px;
          font-weight: {active ? 600 : 500};
          padding: 11px 14px; border-radius: 11px; border: none;
          background: {active ? (item.magic ? 'var(--gold)' : 'var(--ink)') : 'transparent'};
          color: {active ? (item.magic ? '#2C2620' : 'var(--paper)') : item.magic ? 'var(--gold-deep)' : 'var(--ink)'};
        "
      >
        <Icon name={item.icon} size={19} stroke={1.7} />
        {item.label}
        {#if item.magic && !active}
          <span style="margin-left: auto; width: 7px; height: 7px; border-radius: 999px; background: var(--gold); display: block;"></span>
        {/if}
      </button>
    {/each}
  </nav>
</aside>
